module.exports = {
  JWT_SECRET: process.env.JWT_SECRET,
  WIZARD_CDN_API_SECRET: process.env.WIZARD_CDN_API_SECRET,
  ALLOW_GRAPHIQL: process.env.ALLOW_GRAPHIQL,
  GRAPHQL_ENDPOINT: process.env.GRAPHQL_ENDPOINT,
};
